version: '3.1'

services:
    db:
      container_name: compose-docker-mariadb
      image: mariadb:11.2
      restart: always
      environment:
        MARIADB_DATABASE: myDB
        MARIADB_ROOT_PASSWORD: root
      ports:
        - "3306:3306"